### ISSUE TITLE
How to add a note?

### ISSUE THREAD

**Issue by s-pace** [santiher/python-helpscout-v2#1]
👋 @santiher ,

Thank you for your tool. It works great.

How should we create a note to a conversation? I have tried by using some `params` filtering on the `id` or using the same id as the conversation but it didn't work.

Let us know!

**Comment by s-pace** [comment]
👋 @santiher 

Thanks for the details. I have follow this and it didn't work. I will troubleshoot it.

Cheers

**Comment by santiher** [comment]
Hey, just letting you know that I added some changes and now you can do:

```python
from helpscout import HelpScout
client = HelpScout(app_id='ax0912n', app_secret='axon129')
conversation_id = 12102912
client.conversations[conversation_id].notes.post(data={'text': 'My note'})
```

It works in case you couldn't get it to work before, I don't know about attachments.
I'll close the issue later if everything is ok or abandoned ¯\\_(ツ)_/¯

**Comment by s-pace** [comment]
Great! Thanks for the update. I will try to implement it as soon as possible.

**Comment by s-pace** [comment]
Works well thanks.

Closing the first issue!
