### ISSUE TITLE
Sample of creating a new Customer please

### ISSUE THREAD

**Issue by nextcoder** [santiher/python-helpscout-v2#2]
We need an example on how to call the create on the customers using the this library.

**Comment by santiher** [comment]
Hi,
I just realized of the new issue :scream: 
I can't access HelpScout at the moment, so I cannot test creating a new customer, but I believe something like this should work:

```python
> customer_data = {
      "firstName" : "Vernon",
      "lastName" : "Bear",
      "photoUrl" : "https://api.helpscout.net/img/some-avatar.jpg",
      "photoType" : "twitter",
      "jobTitle" : "CEO and Co-Founder",
      "location" : "Greater Dallas/FT Worth Area",
      "background" : "I've worked with Vernon before and he's really great.",
      "age" : "30-35",
      "gender" : "Male",
      "organization" : "Acme, Inc",
      "emails" : [{
          "type" : "work",
          "value" : "bear@acme.com"
          }
      ]
  }
> from helpscout import HelpScout
> helpscout_client = HelpScout(app_id='your_app_id', app_secret='your_secret')
> helpscout_client.customers.post(data=customer_data)
```

Check it out please.

**Comment by nextcoder** [comment]
Yes, we were able to figure out creating a customer.

Now what we needed to do but doesn't seem to be supported is to DELETE a customer that we created. Is this feature disabled due to risk of accidental deletion?

**Comment by santiher** [comment]
It seem that customee delete is not implemented in the API, only get, list, create and update.
[Here](https://developer.helpscout.com/mailbox-api/endpoints/customers/list/) is the documentation.
No idea why it can't be done, you should contact helpscout for that.
